# -*- coding: utf-8 -*-
"""APD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l8S-Is6a6prupogse9nHU1Jqo2zTa2nJ
"""

a = 6
b = 7
c = (a+b)*(a-b)+(a*b)
print(c)